# Generated by Django 4.2.3 on 2023-08-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='desc',
            field=models.TextField(default='hhkhk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='name',
            field=models.CharField(default='mkmk', max_length=250),
            preserve_default=False,
        ),
    ]
