# Generated by Django 4.2.3 on 2023-08-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0002_movies_desc_movies_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='ddd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
